apiVersion: v1
kind: Service
metadata:
   name: user-service
spec:
  type: LoadBalancer
  selector:
       app: user-service
  ports:
      - name: http
        port: 8081
        protocol: TCP
        targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: user-service
   labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
        app: user-service
  template:
    metadata:
        labels:
          app: user-service
    spec:
        containers:
          - name: userservice-server
            resources:
              requests:
                cpu: 200m
                memory: 64Mi
              limits:
                cpu: 300m
                memory: 128Mi
            image: maestre3d/quark-user-service
            ports:
              - containerPort: 8081